### ISSUE TITLE
update_modules() should delete the old directory before copying the new

### ISSUE THREAD

**Issue by notro** [Hexxeh/rpi-update#106]
I'm going to use rpi-update to distribute my own kernel.
In this kernel I have _backlight.o_ as a builtin and not as a loadable module.

rpi-update just copies the new modules on top of the old directory.
This results in the kernel complaining about duplicate symbols, because the old backlight.ko from the prevoius kernel is still present in the directory.

I'm not sure how this deleting should be done.
Delete all /lib/modules/dirs that is present in the update?

I'm not skilled in shell scripting, so I'm not sure how to do this.

**Comment by popcornmix** [comment]
Added patch from @notro https://github.com/Hexxeh/rpi-update/issues/106#issuecomment-23028756

**Comment by notro** [comment]
Thanks
