### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by massimopalmieri** [Hexxeh/rpi-update#122]
Hi,

I'm trying to update the firmware and I'm getting this error. Do you know how to solve it?

 **\* Setting up firmware (this may take a few minutes)
Cloning into '//root/.rpi-firmware'...
git-remote-https: error while loading shared libraries: /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4: invalid ELF header
 !!! Failed to download new firmware files

**Comment by ikay13** [comment]
Did this ever get resolved? I'm having a very similar issue with my Odroid XU4, but I can't find anything related except for this issue report..
