### ISSUE TITLE
[enhancement] Display the version and ask before updating

### ISSUE THREAD

**Issue by szafran81** [Hexxeh/rpi-update#135]
Hi,

First off - very nice work - saves a lot of time and trouble.

It would be nice if the script shown the version that it'll be updating to and ask the user if he'd like to continue with the update.
For eg. I have some problems with the WiFi drivers and I have to wait untill they are available for specified kernel, so knowing what kernel it'll be updating to I can check if I can allready update, or do I have to wait.

______
Szafran

**Comment by Ruffio** [comment]
@szafran81 @popcornmix Even I understand your feature request it doesn't look like that there are that high a demand for it, so I think that unless you provide a PR, I don't think this is going to be implemented. I think this should be closed.

**Comment by popcornmix** [comment]
You can get a list of commit messages that are contained in the update. That should mention if any kernel changes are present.
```
$ sudo UPDATE_SELF=0 JUST_CHECK=1 rpi-update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Firmware update required. New commits available:
======================================================
kernel: Bump to 3.18.16

firmware: dispmanx: Rotate clipped coordinated when display is rotated
See: https://github.com/raspberrypi/firmware/issues/438

firmware: arm_display: Avoid holding lock while waiting for vsync with rotated display
See: https://github.com/raspberrypi/firmware/issues/437

firmware: dispmanx: Fix order of scale and flip for dispmanx_snapshot
See: https://github.com/raspberrypi/firmware/issues/435

firmware: arm_loader: Fix force_core for 2836 and add disable SMP/L2 option

firmware: qpu_execute: Optionally launch qpus explicitly on first N qpus

firmware: qpu_execute: Enable profiling options for qpu_execute
======================================================
kernel: added basic docker support
See: https://github.com/raspberrypi/linux/pull/1020

kernel: BCM270x_DT: Default Compute Module i2c, i2s and spi support

kernel: bcm2835-sdhost: Improve error handling and recovery
See: https://discourse.osmc.tv/t/test-new-raspberry-pi-sd-card-driver/5058/46

firmware: arm_loader: Only add arm/vc i2c aliases if exactly one camera port
```
Any mention of "kernel:" should indicate a kernel upate occurred.
