### ISSUE TITLE
GnuTLS: A TLS warning alert has been received.

### ISSUE THREAD

**Issue by peepo** [Hexxeh/rpi-update#136]
would appreciate a little more info advice.
many thanks
Jonathan

ca-certificates is already the newest version.

$ sudo ntpdate -u ntp.ubuntu.com
17 Apr 09:53:06 ntpdate[2200]: adjust time server 91.189.89.199 offset 0.002577 sec

wfm:
 sudo UPDATE_SELF=0 rpi-update

2 boxes kept mostly offline on separate router,** 
shutdown, change ethernet from local to global router
recently ie quite a few weeks, maybe few months
sudo rpi-update fails:

GnuTLS: A TLS warning alert has been received.
Unable to establish SSL connection.
 !!! Failed to download update for rpi-update!
 !!! Make sure you have ca-certificates installed and that the time is set correctly

**due to BTbroadband router's failure to cope with slightly complicated arrangements...

**Comment by Ruffio** [comment]
@popcornmix it looks like this issue can be closed.
