### ISSUE TITLE
dependency suggestion

### ISSUE THREAD

**Issue by eggy** [Hexxeh/rpi-update#138]
Ran into a small issue recently, curl is not installed by default when installing a minimal raspbain installation. Whomever is in charge of maintaining the raspbain package should update the dependencies to please include curl.

**Comment by Ruffio** [comment]
@asb this has been implemented and an be closed?

**Comment by popcornmix** [comment]
Yes, I believe this was implemented long ago. I get:
```
$ apt-cache depends rpi-update
rpi-update
  Depends: binutils
  Depends: curl
```
@eggy reopen if there is still an issue.
