### ISSUE TITLE
Aug 6 update appears "tainted"

### ISSUE THREAD

**Issue by andrewpmiller** [Hexxeh/rpi-update#146]
The most recent update shows up as tainted. I read [this post](http://www.raspberrypi.org/forums/viewtopic.php?t=62006&p=460976) on the Pi forums, so it seems to be unimportant - but wanted to mention it. 

```
Aug  6 2014 17:55:53 
Copyright (c) 2012 Broadcom
version 3da89bd3cdef7980b684f48fe60944aff4502f50 (tainted) (release)
```

**Comment by crishoj** [comment]
This tainted flag appears again with the latest update:

```
~> /opt/vc/bin/vcgencmd version
Jun 13 2017 14:49:57
Copyright (c) 2012 Broadcom
version 22340f772ce101854acbc46045358dae832dd513 (tainted) (release)
```
