### ISSUE TITLE
Need kernel headers

### ISSUE THREAD

**Issue by droidmunkey** [Hexxeh/rpi-update#148]
dkms build -m 8192cu -v 4.0.29
Error! echo
Your kernel headers for kernel 3.12.26+ cannot be found at
/lib/modules/3.12.26+/build or /lib/modules/3.12.26+/source.

How do i get the headers for your custom kernel?

**Comment by Ruffio** [comment]
@droidmunkey can this be closed?

**Comment by popcornmix** [comment]
Not an rpi-update issue anyway. kernel headers should either come from distribution repo (raspbian) or through a scipt like rpi-source.
