### ISSUE TITLE
failed while doing rpi-update for 2014-09-09-wheezy-raspbian

### ISSUE THREAD

**Issue by carilwang** [Hexxeh/rpi-update#149]
pi@raspberrypi ~ $ sudo rpi-update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7100  100  7100    0     0   9244      0 --:--:-- --:--:-- --:--:-- 13446
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** We're running for the first time
 *** Backing up files (this will take a few minutes)
 *** Backing up firmware
 *** Backing up modules 3.12.28+
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    317      0 --:--:-- --:--:-- --:--:--   449
100 22.8M  100 22.8M    0     0  1213k      0  0:00:19  0:00:19 --:--:-- 1430k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 3.12.28+
 *** Updating VideoCore libraries
 *** Using HardFP libraries
 *** Updating SDK
cp: cannot create directory `//opt/vc/src/hello_pi': Read-only file system
cp: cannot access `//root/.rpi-firmware/vc/sdk/opt/vc/include': Input/output error

**Comment by Ruffio** [comment]
@popcornmix this issue can be closed.
