### ISSUE TITLE
check update

### ISSUE THREAD

**Issue by thib3113** [Hexxeh/rpi-update#150]
Hello,
You'r script is good, thank you, but i have one question. Have you create one option just for check if one update is available ? or not ?

**Comment by ric96** [comment]
Why not make this default so that the firmware is updated only if their is an update is available?
And add a force option to update any way.

**Comment by popcornmix** [comment]
The firmware is only updated if an update is available. Try running rpi-update more than once, it will say firmware is up to date on second run.

**Comment by ric96** [comment]
Huh, my bad should have checked it before.

**Comment by Ruffio** [comment]
@popcornmix I think this issue can be closed.
