### ISSUE TITLE
curl: (7) couldn't connect to host

### ISSUE THREAD

**Issue by splurglepoof** [Hexxeh/rpi-update#154]
Yeah, so I have the newest super greatest  "rpi-update" that uses curl instead of the ancient broken wget 1.13.4 and it still doesn't work.   wget 1.15 on my debian 3.16-2-amd64 desktop works fine, curl 7.38.0 on the desktop works fine but curl 7.26.0 on the rpi doesn't.  Time is fine, using the same time server for both machines.

```pi@raspcam /tmp $ sudo apt-get install ca-certificates```
```Reading package lists... Done```
```Building dependency tree```
```Reading state information... Done```
```ca-certificates is already the newest version.```
```0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.```

```sudo apt-get update && sudo apt-get install rpi-update``` gets me:
```rpi-update is already the newest version.```
```0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.```

But

```pi@raspcam /tmp $ sudo rpi-update```
``` *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom```
```*** Performing self-update```
```  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed```
```  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) couldn't connect to host```
```!!! Failed to download update for rpi-update!```
```!!! Make sure you have ca-certificates installed and that the time is set correctly```

I've looked at bug #65, and I see that the consensus is that everything is fixed.  This does not appear to be the case.

```pi@raspcam /tmp $ uname -a```
```Linux raspcam 3.12.28+ #709 PREEMPT Mon Sep 8 15:28:00 BST 2014 armv6l GNU/Linux```

**Comment by Ruffio** [comment]
@splurglepoof so this can be closed?

**Comment by popcornmix** [comment]
rpi-update just uses curl for network access. It sounds like a general networking/DNS issue, and would be better discussed in the forum.
