### ISSUE TITLE
cannot stat

### ISSUE THREAD

**Issue by gittastic** [Hexxeh/rpi-update#161]
https://github.com/Hexxeh/rpi-update/commit/8c76703ea0f0aee56dd19d459b2565de613317cb

Only had a quick look, but I think this commit has broken things when updating kernel modules.

cp: cannot stat //root/.rpi-firmware/modules/*

Edit: sorry, I think its an error specific to latest rpi-firmware commit 96f2257f57196817ebb030096993823be721fb27

I have downgraded the rpi firmware and no longer get this error.

**Comment by cswingle** [comment]
Can confirm.  I am getting this error, and after rebooting the pi, lsmod shows nothing.  Needless to say, the pi lacks some features now...

**Comment by gittastic** [comment]
Apparently fixed in 67197d9d73c56570578cb2c6c188af263a37ecd9

https://github.com/Hexxeh/rpi-firmware/commit/67197d9d73c56570578cb2c6c188af263a37ecd9

Thanks!
