### ISSUE TITLE
Beware of NEW firmware 3.18.5+, kills i2c bus 

### ISSUE THREAD

**Issue by Radiusxe** [Hexxeh/rpi-update#162]
Hi,
I made many changes at same time (new enclosure, removing some packages, update packages, update firmware; can say shorter I have made great one day maintenance) and then RPI does not sees i2c bus (cannot measure pressure, light intensity and one wire temperature DS18B20). DHT22 WORKS :).

After two days of finding bug in wiring, reinstalling packages and so on, I' ve got idea, new firmware... I have downgrade him and voala, everything WORKS like a CHARM.

magic command is (Linux raspberrypi 3.12.35+ #730 PREEMPT Fri Dec 19 18:31:24 GMT 2014 armv6l GNU/Linux):
[code]sudo rpi-update ba43047bec24d5f0a4150f09a37884240f8926d2[/code]

I have better use 3.12.35+, because firmware 3.12.36+ have freeze me RPI one time.

Radius

**Comment by popcornmix** [comment]
Read here for details of what has changed: http://www.raspberrypi.org/forums/viewtopic.php?f=29&t=97216
Can you try adding config.txt:
dtparam=i2c
