### ISSUE TITLE
sftp-curl-php issues

### ISSUE THREAD

**Issue by jomutts** [Hexxeh/rpi-update#164]
I wanted to connect to sftp but had curl-php issues where i googled and the solutions I got were.
$ curl –version
curl: (6) Could not resolve host: xn--version-t16c

$ sudo apt-get install build-essential debhelper libssh2-1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
debhelper is already the newest version.
libssh2-1-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 133 not upgraded.

$ sudo apt-get source libcurl3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Picking 'curl' as source package instead of 'libcurl3'
E: Unable to find a source package for curl

Resolved this issue by running

$ sudo apt-get install curl libcurl3 libcurl3-dev php5-curl

**Comment by Ruffio** [comment]
@jomutts @popcornmix I can't see that this has anything to do with rpi-update? I suggest it can closed
