### ISSUE TITLE
Random reboot after upgrade

### ISSUE THREAD

**Issue by ljcljc** [Hexxeh/rpi-update#168]
I run 'rpi-update' to update kernel to the latest version, and now it won't be dead, but it randomly reboot for no reason. Sometime it's one hour, sometimes it's 2 hours.

This is when I run 'last reboot'

reboot system boot 3.18.9-v7+ Fri Mar 20 15:46 - 17:54 (02:08)
reboot system boot 3.18.9-v7+ Fri Mar 20 14:17 - 15:46 (01:29)
reboot system boot 3.18.9-v7+ Fri Mar 20 14:03 - 15:46 (01:43)

pi would automatically reboot as I see in /var/log/syslog
```
Mar 20 15:45:48 205-1-1 /USR/SBIN/CRON[4215]: (CRON) info (No MTA installed, discarding output)
Mar 20 15:46:36 205-1-1 shutdown[4310]: shutting down for system reboot
Mar 20 15:46:36 205-1-1 init: Switching to runlevel: 6
Mar 20 15:46:39 205-1-1 mysqld: 150320 15:46:39 [Note] /usr/sbin/mysqld: Normal shutdown
Mar 20 15:46:39 205-1-1 mysqld:
Mar 20 15:46:39 205-1-1 mysqld: 150320 15:46:39 [Note] Event Scheduler: Purging the queue. 0 events
Mar 20 15:46:39 205-1-1 mysqld: 150320 15:46:39 InnoDB: Starting shutdown...
Mar 20 15:46:41 205-1-1 mysqld: 150320 15:46:41 InnoDB: Shutdown completed; log sequence number 718843536
Mar 20 15:46:41 205-1-1 mysqld: 150320 15:46:41 [Note] /usr/sbin/mysqld: Shutdown complete
Mar 20 15:46:41 205-1-1 mysqld:
Mar 20 15:46:42 205-1-1 mysqld_safe: mysqld from pid file /var/run/mysqld/mysqld.pid ended
Mar 20 15:46:47 205-1-1 kernel: imklog 5.8.11, log source = /proc/kmsg started.
Mar 20 15:46:47 205-1-1 rsyslogd: [origin software="rsyslogd" swVersion="5.8.11" x-pid="2010" x-info="http://www.rsyslog.com"] start
Mar 20 15:46:47 205-1-1 kernel: [ 0.000000] Booting Linux on physical CPU 0xf00
Mar 20 15:46:47 205-1-1 kernel: [ 0.000000] Initializing cgroup subsys cpu
Mar 20 15:46:47 205-1-1 kernel: [ 0.000000] Initializing cgroup subsys cpuacct
```
My pi is working perfectly for several months on rpi b+, and has problems after I upgrade. I believe it's a problem with kernel. Can someone help me with that? Thanks

**Comment by popcornmix** [comment]
I can't see a reason for this being kernel related. Looks like a cron job.
Can you revert to an earlier firmware and confirm the problem goes away? Then we can identify the point where it occurred.

From: https://github.com/Hexxeh/rpi-firmware/commits/master
you can find the hash of any firmware update (the hex number at then end of the URL).

Downgrade with:
[code]sudo rpi-update <hash>[/code]

What kernel version were you on before.
Try reverting to a version close to that and check if the issue is present.

**Comment by ljcljc** [comment]
My kernel version is 3.12.28 on pi b+, it's working fine.
Then, I upgrade to 3.18.7 for pi2, it will random be dead, I have to replug the power to reboot it manually.
Now, I am on 3.18.9, it will random reboot, not dead. At least I don't need to unplug and plug the power from time to time.

I cannot go back, because it won't support rpi2 with old version. And I am sure it's not a crob job problem. The only thing I do using cron is to take picture with a webcam, and that should not cause reboot. 

However, it has error message like this:
uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).

But I happened before, nothing happened, and the webcam is working fine. So I just ignore it.

Also, here is my dmesg output if you have interest to read. Thanks.

[ 0.000000] Booting Linux on physical CPU 0xf00
[ 0.000000] Initializing cgroup subsys cpu
[ 0.000000] Initializing cgroup subsys cpuacct
[ 0.000000] Linux version 3.18.9-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #768 SMP PREEMPT Sun Mar 15 19:41:56 GMT 2015
[ 0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[ 0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[ 0.000000] Machine model: Raspberry Pi 2 Model B
[ 0.000000] cma: Reserved 8 MiB at 0x36800000
[ 0.000000] Memory policy: Data cache writealloc
[ 0.000000] On node 0 totalpages: 225280
[ 0.000000] free_area_init_node: node 0, pgdat 80809440, node_mem_map b6113000
[ 0.000000] Normal zone: 1760 pages used for memmap
[ 0.000000] Normal zone: 0 pages reserved
[ 0.000000] Normal zone: 225280 pages, LIFO batch:31
[ 0.000000] [bcm2709_smp_init_cpus] enter (8620->f3003010)
[ 0.000000] [bcm2709_smp_init_cpus] ncores=4
[ 0.000000] PERCPU: Embedded 10 pages/cpu @b60e1000 s11456 r8192 d21312 u40960
[ 0.000000] pcpu-alloc: s11456 r8192 d21312 u40960 alloc=10*4096
[ 0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[ 0.000000] Built 1 zonelists in Zone order, mobility grouping on. Total pages: 223520
[ 0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2709.boardrev=0xa21041 bcm2709.serial=0x76b23710 smsc95xx.macaddr=B8:27:EB:B2:37:10 bcm2708_fb.fbswap=1 bcm
0000 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000 dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait
[ 0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[ 0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[ 0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[ 0.000000] Memory: 875832K/901120K available (5705K kernel code, 397K rwdata, 1740K rodata, 384K init, 763K bss, 25288K reserved)
[ 0.000000] Virtual kernel memory layout:
[ 0.000000] vector : 0xffff0000 - 0xffff1000 ( 4 kB)
[ 0.000000] fixmap : 0xffc00000 - 0xffe00000 (2048 kB)
[ 0.000000] vmalloc : 0xb7800000 - 0xff000000 (1144 MB)
[ 0.000000] lowmem : 0x80000000 - 0xb7000000 ( 880 MB)
[ 0.000000] modules : 0x7f000000 - 0x80000000 ( 16 MB)
[ 0.000000] .text : 0x80008000 - 0x8074d700 (7446 kB)
[ 0.000000] .init : 0x8074e000 - 0x807ae000 ( 384 kB)
[ 0.000000] .data : 0x807ae000 - 0x8081147c ( 398 kB)
[ 0.000000] .bss : 0x8081147c - 0x808d01d4 ( 764 kB)
[ 0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[ 0.000000] Preemptible hierarchical RCU implementation.
[ 0.000000] NR_IRQS:608
[ 0.000000] Architected cp15 timer(s) running at 19.20MHz (virt).
[ 0.000013] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 3579139424256ns
[ 0.000037] Switching to timer-based delay loop, resolution 52ns
[ 0.000339] Console: colour dummy device 80x30
[ 0.001795] console [tty1] enabled
[ 0.001845] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[ 0.001929] pid_max: default: 32768 minimum: 301
[ 0.002332] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[ 0.002393] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[ 0.003671] Initializing cgroup subsys memory
[ 0.003762] Initializing cgroup subsys devices
[ 0.003817] Initializing cgroup subsys freezer
[ 0.003870] Initializing cgroup subsys net_cls
[ 0.003937] Initializing cgroup subsys blkio
[ 0.004048] CPU: Testing write buffer coherency: ok
[ 0.004161] ftrace: allocating 19576 entries in 58 pages
[ 0.052398] CPU0: update cpu_capacity 1024
[ 0.052478] CPU0: thread -1, cpu 0, socket 15, mpidr 80000f00
[ 0.052518] [bcm2709_smp_prepare_cpus] enter
[ 0.052680] Setting up static identity map for 0x525438 - 0x52546c
[ 0.112326] [bcm2709_boot_secondary] cpu:1 started (0) 18
[ 0.112632] CPU1: Booted secondary processor
[ 0.112641] [bcm2709_secondary_init] enter cpu:1
[ 0.112690] CPU1: update cpu_capacity 1024
[ 0.112699] CPU1: thread -1, cpu 1, socket 15, mpidr 80000f01
[ 0.132301] [bcm2709_boot_secondary] cpu:2 started (0) 18
[ 0.132557] CPU2: Booted secondary processor
[ 0.132563] [bcm2709_secondary_init] enter cpu:2
[ 0.132592] CPU2: update cpu_capacity 1024
[ 0.132601] CPU2: thread -1, cpu 2, socket 15, mpidr 80000f02
[ 0.152377] [bcm2709_boot_secondary] cpu:3 started (0) 17
[ 0.152622] CPU3: Booted secondary processor
[ 0.152628] [bcm2709_secondary_init] enter cpu:3
[ 0.152656] CPU3: update cpu_capacity 1024
[ 0.152664] CPU3: thread -1, cpu 3, socket 15, mpidr 80000f03
[ 0.152760] Brought up 4 CPUs
[ 0.152892] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[ 0.152926] CPU: All CPU(s) started in SVC mode.
[ 0.153944] devtmpfs: initialized
[ 0.178638] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[ 0.180672] pinctrl core: initialized pinctrl subsystem
[ 0.183767] NET: Registered protocol family 16
[ 0.189374] DMA: preallocated 4096 KiB pool for atomic coherent allocations
[ 0.190530] bcm2709.uart_clock = 3000000
[ 0.193282] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[ 0.193338] hw-breakpoint: maximum watchpoint size is 8 bytes.
[ 0.193397] mailbox: Broadcom VideoCore Mailbox driver
[ 0.193533] bcm2708_vcio: mailbox at f300b880
[ 0.193893] bcm_power: Broadcom power driver
[ 0.193931] bcm_power_open() -> 0
[ 0.193958] bcm_power_request(0, 8)
[ 0.694637] bcm_mailbox_read -> 00000080, 0
[ 0.694671] bcm_power_request -> 0
[ 0.694820] Serial: AMBA PL011 UART driver
[ 0.694971] dev:f1: ttyAMA0 at MMIO 0x3f201000 (irq = 83, base_baud = 0) is a PL011 rev3
[ 0.764981] SCSI subsystem initialized
[ 0.765274] usbcore: registered new interface driver usbfs
[ 0.765410] usbcore: registered new interface driver hub
[ 0.765581] usbcore: registered new device driver usb
[ 0.767450] Switched to clocksource arch_sys_counter
[ 0.797749] FS-Cache: Loaded
[ 0.798093] CacheFiles: Loaded
[ 0.809316] NET: Registered protocol family 2
[ 0.810749] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[ 0.810937] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[ 0.811171] TCP: Hash tables configured (established 8192 bind 8192)
[ 0.811306] TCP: reno registered
[ 0.811344] UDP hash table entries: 512 (order: 2, 16384 bytes)
[ 0.811430] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[ 0.811799] NET: Registered protocol family 1
[ 0.812419] RPC: Registered named UNIX socket transport module.
[ 0.812465] RPC: Registered udp transport module.
[ 0.812497] RPC: Registered tcp transport module.
[ 0.812527] RPC: Registered tcp NFSv4.1 backchannel transport module.
[ 0.813502] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 5 counters available
[ 0.813800] bcm2708_dma: DMA manager at f3007000
[ 0.813991] vc-mem: phys_addr:0x00000000 mem_base=0x3dc00000 mem_size:0x3f000000(1008 MiB)
[ 0.815565] futex hash table entries: 1024 (order: 4, 65536 bytes)
[ 0.815835] audit: initializing netlink subsys (disabled)
[ 0.815926] audit: type=2000 audit(0.789:1): initialized
[ 0.832252] VFS: Disk quotas dquot_6.5.2
[ 0.832650] Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[ 0.835644] FS-Cache: Netfs 'nfs' registered for caching
[ 0.836718] NFS: Registering the id_resolver key type
[ 0.836816] Key type id_resolver registered
[ 0.836847] Key type id_legacy registered
[ 0.838112] msgmni has been set to 1726
[ 0.839957] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[ 0.840195] io scheduler noop registered
[ 0.840243] io scheduler deadline registered (default)
[ 0.840611] io scheduler cfq registered
[ 0.843252] BCM2708FB: allocated DMA memory f6c00000
[ 0.843321] BCM2708FB: allocated DMA channel 0 @ f3007000
[ 0.849048] Console: switching to colour frame buffer device 82x26
[ 0.854814] bcm2708-dmaengine bcm2708-dmaengine: Load BCM2835 DMA engine driver
[ 0.856773] uart-pl011 dev:f1: no DMA platform data
[ 0.858966] vc-cma: Videocore CMA driver
[ 0.860540] vc-cma: vc_cma_base = 0x00000000
[ 0.862086] vc-cma: vc_cma_size = 0x00000000 (0 MiB)
[ 0.863609] vc-cma: vc_cma_initial = 0x00000000 (0 MiB)
[ 0.876695] brd: module loaded
[ 0.883897] loop: module loaded
[ 0.885598] vchiq: vchiq_init_state: slot_zero = 0xb6800000, is_master = 0
[ 0.887855] Loading iSCSI transport class v2.0-870.
[ 0.890259] usbcore: registered new interface driver smsc95xx
[ 0.891846] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[ 1.093721] Core Release: 2.80a
[ 1.095214] Setting default values for core params
[ 1.096702] Finished setting default values for core params
[ 1.298614] Using Buffer DMA mode
[ 1.300089] Periodic Transfer Interrupt Enhancement - disabled
[ 1.301628] Multiprocessor Interrupt Enhancement - disabled
[ 1.303174] OTG VER PARAM: 0, OTG VER FLAG: 0
[ 1.304740] Dedicated Tx FIFOs mode
[ 1.306584] WARN::dwc_otg_hcd_init:1047: FIQ DMA bounce buffers: virt = 0xb6c14000 dma = 0xf6c14000 len=9024
[ 1.309733] FIQ FSM acceleration enabled for :
[ 1.309733] Non-periodic Split Transactions
[ 1.309733] Periodic Split Transactions
[ 1.309733] High-Speed Isochronous Endpoints
[ 1.315939] dwc_otg: Microframe scheduler enabled
[ 1.316015] WARN::hcd_init_fiq:412: FIQ on core 1 at 0x803d6a28
[ 1.317667] WARN::hcd_init_fiq:413: FIQ ASM at 0x803d6d84 length 36
[ 1.319329] WARN::hcd_init_fiq:438: MPHI regs_base at 0xb780a000
[ 1.320954] dwc_otg bcm2708_usb: DWC OTG Controller
[ 1.322580] dwc_otg bcm2708_usb: new USB bus registered, assigned bus number 1
[ 1.324236] dwc_otg bcm2708_usb: irq 32, io mem 0x00000000
[ 1.325863] Init: Port Power? op_state=1
[ 1.327405] Init: Power Port (0)
[ 1.329219] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[ 1.330823] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[ 1.332411] usb usb1: Product: DWC OTG Controller
[ 1.333960] usb usb1: Manufacturer: Linux 3.18.9-v7+ dwc_otg_hcd
[ 1.335523] usb usb1: SerialNumber: bcm2708_usb
[ 1.337964] hub 1-0:1.0: USB hub found
[ 1.339540] hub 1-0:1.0: 1 port detected
[ 1.341457] dwc_otg: FIQ enabled
[ 1.341471] dwc_otg: NAK holdoff enabled
[ 1.341482] dwc_otg: FIQ split-transaction FSM enabled
[ 1.341521] Module dwc_common_port init
[ 1.341903] usbcore: registered new interface driver usb-storage
[ 1.343630] mousedev: PS/2 mouse device common for all mice
[ 1.345746] bcm2835-cpufreq: min=600000 max=900000
[ 1.347612] sdhci: Secure Digital Host Controller Interface driver
[ 1.349145] sdhci: Copyright(c) Pierre Ossman
[ 1.350860] DMA channels allocated for the MMC driver
[ 1.387487] Load BCM2835 MMC driver
[ 1.390729] sdhci-pltfm: SDHCI platform and OF driver helper
[ 1.397354] ledtrig-cpu: registered to indicate activity on CPUs
[ 1.399260] hidraw: raw HID events driver (C) Jiri Kosina
[ 1.402171] usbcore: registered new interface driver usbhid
[ 1.404823] usbhid: USB HID core driver
[ 1.410873] TCP: cubic registered
[ 1.412493] Initializing XFRM netlink socket
[ 1.415210] NET: Registered protocol family 17
[ 1.417689] Key type dns_resolver registered
[ 1.419564] Registering SWP/SWPB emulation handler
[ 1.421974] registered taskstats version 1
[ 1.423738] vc-sm: Videocore shared memory driver
[ 1.425229] [vc_sm_connected_init]: start
[ 1.427541] [vc_sm_connected_init]: end - returning 0
[ 1.430146] Waiting for root device /dev/mmcblk0p2...
[ 1.447801] mmc0: host does not support reading read-only switch, assuming write-enable
[ 1.454316] mmc0: new high speed SDHC card at address aaaa
[ 1.456468] mmcblk0: mmc0:aaaa SU16G 14.8 GiB
[ 1.462163] mmcblk0: p1 p2
[ 1.537932] Indeed it is in host mode hprt0 = 00021501
[ 1.563028] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[ 1.566150] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[ 1.577666] devtmpfs: mounted
[ 1.579912] Freeing unused kernel memory: 384K (8074e000 - 807ae000)
[ 1.727582] usb 1-1: new high-speed USB device number 2 using dwc_otg
[ 1.729505] Indeed it is in host mode hprt0 = 00001101
[ 1.927868] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[ 1.929741] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 1.932480] hub 1-1:1.0: USB hub found
[ 1.934381] hub 1-1:1.0: 5 ports detected
[ 2.217905] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[ 2.317999] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[ 2.322202] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 2.327713] smsc95xx v1.0.4
[ 2.391285] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:b2:37:10
[ 2.859906] udevd[197]: starting version 175
[ 3.147702] usb 1-1.4: new high-speed USB device number 4 using dwc_otg
[ 3.325470] usb 1-1.4: New USB device found, idVendor=1e4e, idProduct=0109
[ 3.329965] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 3.332492] usb 1-1.4: Product: USB2.0 Camera
[ 3.334718] usb 1-1.4: Manufacturer: Etron Technology, Inc.
[ 3.786494] media: Linux media interface: v0.10
[ 3.806159] Linux video capture interface: v2.00
[ 3.841906] uvcvideo: Found UVC 1.00 device USB2.0 Camera (1e4e:0109)
[ 3.847071] uvcvideo: UVC non compliance - GET_DEF(PROBE) not supported. Enabling workaround.
[ 3.853420] input: USB2.0 Camera as /devices/platform/bcm2708_usb/usb1/1-1/1-1.4/1-1.4:1.0/input/input0
[ 3.857667] usbcore: registered new interface driver uvcvideo
[ 3.859845] USB Video Class driver (1.1.1)
[ 3.982025] usb 1-1.4: Warning! Unlikely big volume range (=4096), cval->res is probably wrong.
[ 3.985976] usb 1-1.4: [3] FU [Mic Capture Volume] ch = 1, val = -4097/-1/1
[ 3.989020] usbcore: registered new interface driver snd-usb-audio
[ 5.622288] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[ 5.919825] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[ 6.507733] i2c /dev entries driver
[ 6.610615] lirc_dev: IR Remote Control driver registered, major 245
[ 6.659289] lirc_rpi: module is from the staging directory, the quality is unknown, you have been warned.
[ 6.669313] lirc_rpi: gpio chip not found!
[ 9.071929] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[ 10.593671] random: dd urandom read with 125 bits of entropy available
[ 11.079653] random: nonblocking pool is initialized
[ 11.100826] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[ 12.552590] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1
[ 17.430230] lirc_rpi: module is from the staging directory, the quality is unknown, you have been warned.
[ 17.437502] lirc_rpi: gpio chip not found!
[ 22.673839] ip_tables: (C) 2000-2006 Netfilter Core Team
[ 373.588235] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 674.420659] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 854.280900] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 1275.053744] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 1453.708466] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 1808.639728] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 2059.469137] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 2427.624575] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 2801.499533] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 3079.373394] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 3081.085504] uvcvideo: Failed to resubmit video URB (-1).
[ 3254.291254] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 3627.569133] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 3629.252706] uvcvideo: Failed to resubmit video URB (-1).
[ 3863.486070] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 4262.473649] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 4469.283906] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 4816.051512] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 5069.844567] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 5408.636693] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 5642.583470] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 5951.223345] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 6330.229578] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 6578.240840] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 6855.174948] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 6856.973911] uvcvideo: Failed to resubmit video URB (-1).
[ 7146.162878] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).
[ 7472.168087] uvcvideo: Failed to query (GET_DEF) UVC control 5 on unit 3: -32 (exp. 1).

**Comment by popcornmix** [comment]
Does it reboot when you access the camera? Might be a power supply issue and enabling the camera causes a voltage drop and reboots the Pi.

Can you try a different power supply or measure the voltage when running with camera working?

**Comment by ljcljc** [comment]
No. I took camera every 5 minutes. It's usually fine. I will try a different power.

And do you know at what power voltage it will reboot? What's the required power range for pi2?

**Comment by popcornmix** [comment]
Pi needs 5V +/- 5%
You need to measure the voltage when under load (e.g. with camera running).

**Comment by Ruffio** [comment]
@ljcljc is this still an issue?

**Comment by ljcljc** [comment]
Yes. I had to switch back to old B+ version of Pi, and there is no problem
then.

On Mon, Jun 15, 2015 at 12:35 AM, Rasmus Christiansen <
notifications@github.com> wrote:

> @ljcljc <https://github.com/ljcljc> is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hexxeh/rpi-update/issues/168#issuecomment-111847732>.
>



-- 
Best wishes

Jiechao Li

**Comment by popcornmix** [comment]
Is the B+ happy with latest kernel?
I'm sure this is a power supply issue.

**Comment by ljcljc** [comment]
Yes. B+ is stable without any problem. I have tried many different power
with RPI 2, but none of them work, after then I just gave up.

On Mon, Jun 15, 2015 at 7:35 PM, popcornmix <notifications@github.com>
wrote:

> Is the B+ happy with latest kernel?
> I'm sure this is a power supply issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hexxeh/rpi-update/issues/168#issuecomment-112026909>.
>



-- 
Best wishes

Jiechao Li

**Comment by Ruffio** [comment]
@ljcljc can this be closed or how do we her any further? I'm thinking that the issue is/was locally else we would have seen a lot of people writting in hear.

**Comment by Ruffio** [comment]
@ljcljc is this still an issue? I'm thinking that the issue is/was locally else we would have seen a lot of people writting in here... Please consider closing this issue. Thanks.

**Comment by ljcljc** [comment]
ok, I will close it
