### ISSUE TITLE
Cannot connect to the update server through the corporate proxy

### ISSUE THREAD

**Issue by sbisbip** [Hexxeh/rpi-update#175]
Some trouble with the command curl when the proxy like at my company filters the ssl connection trough the proxy. To solve the problem I use the option '-k' with the curl command.

The fix could be done with an optional argument or variable.

Thanks a lot
Best regards
Stephane

**Comment by Ruffio** [comment]
@sbisbip when using the option -k you allow curl to use insecure connections thereby making the Pi more vulnable to man-in-the-middle attacks and someone could potentially inject a backdoor with the update. I would not recommend this as a standard feature of rpi-update. This 'issue' should be closed as not going to implement IMHO.
