### ISSUE TITLE
Feature request: -Y option to force update if any available

### ISSUE THREAD

**Issue by Ruffio** [Hexxeh/rpi-update#181]
I'm building a web interface to control the RPi and it would be nice if there could be added a -y option, so if there are any updates available, the update is performed automatically.

I have tried various options but cant find options or man pages that can tell me if such an option exists.

**Comment by tundra-git** [comment]
I also very much want this ability.   I want to be able to execute this program under automated workflows.  Forcing user interfaction will break such tool (tsshbatch, capistrano, ansible, rundeck ...)

**Comment by tundra-git** [comment]
It seems that doing this first, gives desired behavior:

   export SKIP_WARNING=1

Is this a new feature or was it there and I just missed it in the doc somehow?

**Comment by Ruffio** [comment]
How exactly do you do this? The other options are set like: sudo XXXX
rpi-update

**Comment by popcornmix** [comment]
```sudo SKIP_WARNING=1 rpi-update```
would also work (they both just set a env variable).

**Comment by Ruffio** [comment]
Thanks, this works perfectly :-)

It should be documented so no one is in doubt.
