### ISSUE TITLE
[New Feature Request]  Auto Reboot On Upgrade

### ISSUE THREAD

**Issue by tundratim** [Hexxeh/rpi-update#186]
Again, in the spirit of supporting automated workflows, it would be nice to have an option to kick off a reboot automatically if the firmware gets upgraded.

**Comment by popcornmix** [comment]
Anything wrong with:
```sudo rpi-update && sudo reboot```

**Comment by tundra-git** [comment]
Does rpi-update set the error level such that this would not reboot if there were no firmware update?

**Comment by tundra-git** [comment]
I just checked:  rpi-update always sets exit code to 0 regardless of whether there was a firmware update or not, so the above solution will ALWAYS reboot.  What I want is reboot only if there has been a firmware update.

**Comment by Ruffio** [comment]
Duplicate of https://github.com/Hexxeh/rpi-update/issues/157 ?

**Comment by tundratim** [comment]
Yes, they appear to be essentially identical issues.
