### ISSUE TITLE
Not upgrading kernel version on Ubuntu mate 

### ISSUE THREAD

**Issue by fenque** [Hexxeh/rpi-update#189]
Latest raspbian converted to devuan using http://packages.devuan.org/devuan/pool/main/d/devuan-baseconf/.
After reboot kernel not changes.

**Comment by popcornmix** [comment]
Sorry, rpi-update is designed for raspbian.
Other distributions are not supported (and in fact rpi-update may break distributions that don't have use the raspbian kernel and file system layout).
If it doesn't work it suggests boot partition of sdcard is not mapped to /boot, but that is a question for the Ubuntu Mate maintainers.
