### ISSUE TITLE
error running rpi-update curl: (6) Couldn't resolve host 'github.com'

### ISSUE THREAD

**Issue by TheQuestor** [Hexxeh/rpi-update#190]
When running rpi-update I now get an error that it can't resolve host github.com
 *** Downloading specific firmware revision (this will take a few minutes)
curl: (6) Couldn't resolve host 'github.com'

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

but I am able to ping it just fine

PING github.com (192.30.252.128) 56(84) bytes of data.
64 bytes from github.com (192.30.252.128): icmp_req=1 ttl=49 time=54.3 ms
64 bytes from github.com (192.30.252.128): icmp_req=2 ttl=49 time=53.9 ms
64 bytes from github.com (192.30.252.128): icmp_req=3 ttl=49 time=77.1 ms
64 bytes from github.com (192.30.252.128): icmp_req=4 ttl=49 time=51.2 ms

**Comment by popcornmix** [comment]
Can you run:
``curl -L https://github.com/Hexxeh/rpi-firmware/archive/master.tar.gz > /dev/null``

and report the output?

**Comment by Ruffio** [comment]
@TheQuestor is this still an issue? If yes please back with @popcornmix suggestion or close this issue if it is not relevant anymore.

**Comment by TheQuestor** [comment]
It is working now but oddly not until I did a "sudo apt-get install ca-certificates" but yah I just did a "sudo rpi-update" and it all went through just fine but now my spi is no longer working sigh. and in X the taskbar keeps coming on and going off. The 5" TFT + Touch screen is working ok but it is all messed up. I should not have done this without backing up first :(

here is a video of what it is doing now.
https://youtu.be/TviZnNV8oys

going to try a dist-upgrade to see if it fixes it.

**Comment by Ruffio** [comment]
@TheQuestor As the original issue is solved this should be closed then

**Comment by TheQuestor** [comment]
Here is what I did 

pi@rpi2 /devel $ curl -L https://github.com/Hexxeh/rpi-firmware/archive/master.tar.gz
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
pi@rpi2 /devel $ git config --global http.sslVerify true
pi@rpi2 /devel $ sudo apt-get install ca-certificates

pi@rpi2 /devel $ sudo rpi-update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
#############################################################
WARNING: This update bumps to rpi-4.4.y linux tree
Be aware there could be compatibility issues with some drivers
Discussion here:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=144087
##############################################################
Would you like to proceed? (y/N)
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    493      0 --:--:-- --:--:-- --:--:--   721
100 50.4M  100 50.4M    0     0   862k      0  0:00:59  0:00:59 --:--:--  208k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 4.4.8-v7+
 *** depmod 4.4.8+
 *** Updating VideoCore libraries
 *** Using HardFP libraries
 *** Updating SDK
 *** Running ldconfig
 *** Storing current firmware revision
 *** Deleting downloaded files
 *** Syncing changes to disk
 *** If no errors appeared, your firmware was successfully updated to 384626a4e08d49262fd0ebb799b82f330ca7a0df
 *** A reboot is needed to activate the new firmware

pi@rpi2 /boot $ sudo reboot

and whilst the original issue seems to be fixed the result is far from good :(

but as requested I will close this and format my SD Card and start over from scratch [not happy sigh]

just for reference here is my dmesg

`pi@rpi2 ~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0xf00
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 4.4.8-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #880 SMP Fri Apr 22 21:55:04 BST 2016
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine model: Raspberry Pi 2 Model B Rev 1.1
[    0.000000] cma: Reserved 8 MiB at 0x36800000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 225280
[    0.000000] free_area_init_node: node 0, pgdat 808bed80, node_mem_map b6036000
[    0.000000]   Normal zone: 1980 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 225280 pages, LIFO batch:31
[    0.000000] [bcm2709_smp_init_cpus] enter (9520->f3003010)
[    0.000000] [bcm2709_smp_init_cpus] ncores=4
[    0.000000] PERCPU: Embedded 13 pages/cpu @b5ff3000 s22592 r8192 d22464 u53248
[    0.000000] pcpu-alloc: s22592 r8192 d22464 u53248 alloc=13*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 223300
[    0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=480 bcm2709.boardrev=0xa21041 bcm2709.serial=0x5204dc25 smsc95xx.macaddr=B8:27:EB:04:DC:25 bcm2708_fb.fbswap=1 bcm2709.uart_clock=3000000 bcm2709.disk_led_gpio=47 bcm2709.disk_led_active_low=0 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=tty1 console=ttyAMA0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 874136K/901120K available (6336K kernel code, 432K rwdata, 1712K rodata, 476K init, 764K bss, 18792K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0xb7800000 - 0xff800000   (1152 MB)
[    0.000000]     lowmem  : 0x80000000 - 0xb7000000   ( 880 MB)
[    0.000000]     modules : 0x7f000000 - 0x80000000   (  16 MB)
[    0.000000]       .text : 0x80008000 - 0x807e4308   (8049 kB)
[    0.000000]       .init : 0x807e5000 - 0x8085c000   ( 476 kB)
[    0.000000]       .data : 0x8085c000 - 0x808c8088   ( 433 kB)
[    0.000000]        .bss : 0x808cb000 - 0x8098a1ac   ( 765 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000]  Build-time adjustment of leaf fanout to 32.
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] Architected cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000012] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000033] Switching to timer-based delay loop, resolution 52ns
[    0.000355] Console: colour dummy device 80x30
[    0.001543] console [tty1] enabled
[    0.001595] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.001673] pid_max: default: 32768 minimum: 301
[    0.002089] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002143] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.003371] Disabling cpuset control group subsystem
[    0.003454] Initializing cgroup subsys io
[    0.003518] Initializing cgroup subsys memory
[    0.003597] Initializing cgroup subsys devices
[    0.003651] Initializing cgroup subsys freezer
[    0.003702] Initializing cgroup subsys net_cls
[    0.003798] CPU: Testing write buffer coherency: ok
[    0.003914] ftrace: allocating 21191 entries in 63 pages
[    0.056182] CPU0: update cpu_capacity 1024
[    0.056261] CPU0: thread -1, cpu 0, socket 15, mpidr 80000f00
[    0.056300] [bcm2709_smp_prepare_cpus] enter
[    0.056450] Setting up static identity map for 0x8240 - 0x8274
[    0.058854] [bcm2709_boot_secondary] cpu:1 started (0) 17
[    0.059288] [bcm2709_secondary_init] enter cpu:1
[    0.059346] CPU1: update cpu_capacity 1024
[    0.059354] CPU1: thread -1, cpu 1, socket 15, mpidr 80000f01
[    0.059938] [bcm2709_boot_secondary] cpu:2 started (0) 18
[    0.060296] [bcm2709_secondary_init] enter cpu:2
[    0.060325] CPU2: update cpu_capacity 1024
[    0.060334] CPU2: thread -1, cpu 2, socket 15, mpidr 80000f02
[    0.060879] [bcm2709_boot_secondary] cpu:3 started (0) 17
[    0.061134] [bcm2709_secondary_init] enter cpu:3
[    0.061163] CPU3: update cpu_capacity 1024
[    0.061172] CPU3: thread -1, cpu 3, socket 15, mpidr 80000f03
[    0.061258] Brought up 4 CPUs
[    0.061369] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.061403] CPU: All CPU(s) started in HYP mode.
[    0.061433] CPU: Virtualization extensions available.
[    0.062373] devtmpfs: initialized
[    0.074713] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    0.075220] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.076292] pinctrl core: initialized pinctrl subsystem
[    0.077105] NET: Registered protocol family 16
[    0.082953] DMA: preallocated 4096 KiB pool for atomic coherent allocations
[    0.091648] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.091712] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.091942] Serial: AMBA PL011 UART driver
[    0.092300] 3f201000.uart: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    0.597798] console [ttyAMA0] enabled
[    0.602103] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.679660] bcm2835-dma 3f007000.dma: DMA legacy API manager at f3007000, dmachans=0x1
[    0.689748] SCSI subsystem initialized
[    0.693766] usbcore: registered new interface driver usbfs
[    0.699416] usbcore: registered new interface driver hub
[    0.704897] usbcore: registered new device driver usb
[    0.720062] raspberrypi-firmware soc:firmware: Attached to firmware from 2016-04-27 11:10
[    0.755870] clocksource: Switched to clocksource arch_sys_counter
[    0.815184] FS-Cache: Loaded
[    0.818547] CacheFiles: Loaded
[    0.838108] NET: Registered protocol family 2
[    0.843753] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.851023] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.857693] TCP: Hash tables configured (established 8192 bind 8192)
[    0.864230] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.870250] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.876982] NET: Registered protocol family 1
[    0.881833] RPC: Registered named UNIX socket transport module.
[    0.887824] RPC: Registered udp transport module.
[    0.892545] RPC: Registered tcp transport module.
[    0.897282] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.905193] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 5 counters available
[    0.915114] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.937202] VFS: Disk quotas dquot_6.6.0
[    0.941522] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.951400] FS-Cache: Netfs 'nfs' registered for caching
[    0.957918] NFS: Registering the id_resolver key type
[    0.963074] Key type id_resolver registered
[    0.967308] Key type id_legacy registered
[    0.974456] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    0.982126] io scheduler noop registered
[    0.986115] io scheduler deadline registered (default)
[    0.991331] io scheduler cfq registered
[    0.998157] BCM2708FB: allocated DMA memory f6c00000
[    1.003177] BCM2708FB: allocated DMA channel 0 @ f3007000
[    1.016255] Console: switching to colour frame buffer device 100x30
[    1.957107] bcm2835-rng 3f104000.rng: hwrng registered
[    1.964778] vc-cma: Videocore CMA driver
[    1.971090] vc-cma: vc_cma_base      = 0x00000000
[    1.978124] vc-cma: vc_cma_size      = 0x00000000 (0 MiB)
[    1.985774] vc-cma: vc_cma_initial   = 0x00000000 (0 MiB)
[    1.993715] vc-mem: phys_addr:0x00000000 mem_base=0x3dc00000 mem_size:0x3f000000(1008 MiB)
[    2.025040] brd: module loaded
[    2.041767] loop: module loaded
[    2.048317] vchiq: vchiq_init_state: slot_zero = 0xb6c80000, is_master = 0
[    2.059270] Loading iSCSI transport class v2.0-870.
[    2.067418] usbcore: registered new interface driver smsc95xx
[    2.075581] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    2.284130] Core Release: 2.80a
[    2.289635] Setting default values for core params
[    2.296759] Finished setting default values for core params
[    2.505025] Using Buffer DMA mode
[    2.510594] Periodic Transfer Interrupt Enhancement - disabled
[    2.518700] Multiprocessor Interrupt Enhancement - disabled
[    2.526520] OTG VER PARAM: 0, OTG VER FLAG: 0
[    2.533099] Dedicated Tx FIFOs mode
[    2.539269] WARN::dwc_otg_hcd_init:1047: FIQ DMA bounce buffers: virt = 0xb6c14000 dma = 0xf6c14000 len=9024
[    2.553777] FIQ FSM acceleration enabled for :
[    2.553777] Non-periodic Split Transactions
[    2.553777] Periodic Split Transactions
[    2.553777] High-Speed Isochronous Endpoints
[    2.553777] Interrupt/Control Split Transaction hack enabled
[    2.587435] dwc_otg: Microframe scheduler enabled
[    2.587515] WARN::hcd_init_fiq:413: FIQ on core 1 at 0x804455cc
[    2.595770] WARN::hcd_init_fiq:414: FIQ ASM at 0x8044593c length 36
[    2.604339] WARN::hcd_init_fiq:439: MPHI regs_base at 0xb787e000
[    2.612680] dwc_otg 3f980000.usb: DWC OTG Controller
[    2.619979] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    2.629676] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    2.637659] Init: Port Power? op_state=1
[    2.643948] Init: Power Port (0)
[    2.649779] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    2.658919] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.668515] usb usb1: Product: DWC OTG Controller
[    2.675526] usb usb1: Manufacturer: Linux 4.4.8-v7+ dwc_otg_hcd
[    2.683770] usb usb1: SerialNumber: 3f980000.usb
[    2.691718] hub 1-0:1.0: USB hub found
[    2.697795] hub 1-0:1.0: 1 port detected
[    2.704675] dwc_otg: FIQ enabled
[    2.704688] dwc_otg: NAK holdoff enabled
[    2.704698] dwc_otg: FIQ split-transaction FSM enabled
[    2.704739] Module dwc_common_port init
[    2.705092] usbcore: registered new interface driver usb-storage
[    2.713756] mousedev: PS/2 mouse device common for all mice
[    2.722510] bcm2835-cpufreq: min=600000 max=700000
[    2.729920] sdhci: Secure Digital Host Controller Interface driver
[    2.738383] sdhci: Copyright(c) Pierre Ossman
[    2.745346] sdhost: log_buf @ b6c13000 (f6c13000)
[    2.825913] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    2.833953] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.842578] ledtrig-cpu: registered to indicate activity on CPUs
[    2.850973] hidraw: raw HID events driver (C) Jiri Kosina
[    2.858797] usbcore: registered new interface driver usbhid
[    2.866584] usbhid: USB HID core driver
[    2.873296] Initializing XFRM netlink socket
[    2.879822] NET: Registered protocol family 17
[    2.883656] mmc0: host does not support reading read-only switch, assuming write-enable
[    2.885767] mmc0: new high speed SDHC card at address 0007
[    2.886662] mmcblk0: mmc0:0007 SD16G 14.5 GiB
[    2.888303]  mmcblk0: p1 p2
[    2.916421] Indeed it is in host mode hprt0 = 00021501
[    2.916512] Key type dns_resolver registered
[    2.917127] Registering SWP/SWPB emulation handler
[    2.918169] registered taskstats version 1
[    2.918473] vc-sm: Videocore shared memory driver
[    2.918485] [vc_sm_connected_init]: start
[    2.926413] [vc_sm_connected_init]: end - returning 0
[    2.926686] of_cfs_init
[    2.926803] of_cfs_init: OK
[    2.973638] uart-pl011 3f201000.uart: no DMA platform data
[    2.999204] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    3.009710] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    3.020021] devtmpfs: mounted
[    3.026013] Freeing unused kernel memory: 476K (807e5000 - 8085c000)
[    3.145938] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    3.155127] Indeed it is in host mode hprt0 = 00001101
[    3.356317] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    3.365447] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.376088] hub 1-1:1.0: USB hub found
[    3.382367] hub 1-1:1.0: 5 ports detected
[    3.665976] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    3.786344] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    3.795646] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.809002] smsc95xx v1.0.4
[    3.881103] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:04:dc:25
[    3.976008] usb 1-1.5: new high-speed USB device number 4 using dwc_otg
[    4.096971] usb 1-1.5: New USB device found, idVendor=0bda, idProduct=0179
[    4.106671] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.116781] usb 1-1.5: Product: 802.11n NIC
[    4.123616] usb 1-1.5: Manufacturer: Realtek
[    4.130711] usb 1-1.5: SerialNumber: 08D83302BBA7
[    4.186685] udevd[200]: starting version 175
[    4.661639] Driver for 1-wire Dallas network protocol.
[    4.728591] w1-gpio onewire@0: gpio pin 4, external pullup pin 1, parasitic power 0
[    4.781185] w1_add_master_device: set_pullup requires write_byte or touch_bit, disabling
[    4.792529] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    4.820582] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    4.882077] bcm2708_i2c 3f804000.i2c: BSC1 Controller at 0x3f804000 (irq 83) (baudrate 100000)
[    5.109362] ads7846 spi0.1: touchscreen, irq 191
[    5.122072] input: ADS7846 Touchscreen as /devices/platform/soc/3f204000.spi/spi_master/spi0/spi0.1/input/input0
[    5.274849] r8188eu: module is from the staging directory, the quality is unknown, you have been warned.
[    5.311329] Chip Version Info: CHIP_8188E_Normal_Chip_TSMC_D_CUT_1T1R_RomVer(0)
[    5.353709] usbcore: registered new interface driver r8188eu
[    6.762072] w1_master_driver w1_bus_master1: w1_search: max_slave_count 64 reached, will continue next search.
[    6.900459] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    7.148277] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    7.706226] i2c /dev entries driver
[   11.263265] random: dd urandom read with 99 bits of entropy available
[   11.617508] random: nonblocking pool is initialized
[   12.256392] MAC Address = 08:d8:33:02:bb:a7
[   12.266933] R8188EU: ERROR indicate disassoc
[   12.278254] R8188EU: ERROR indicate disassoc
[   12.391850] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   13.673014] R8188EU: ERROR assoc success
[   17.991019] Adding 102396k swap on /var/swap.  Priority:-1 extents:2 across:2134012k SSFS
[   54.253483] w1_master_driver w1_bus_master1: Family 0 for 00.800000000000.8c is not registered.
[  113.769689] w1_master_driver w1_bus_master1: Family 0 for 00.400000000000.46 is not registered.
[  161.299661] w1_master_driver w1_bus_master1: Family 0 for 00.c00000000000.ca is not registered.
[  232.889401] w1_master_driver w1_bus_master1: Family 0 for 00.200000000000.23 is not registered.
[  292.470707] w1_master_driver w1_bus_master1: Family 0 for 00.a00000000000.af is not registered.
[  327.957047] w1_master_driver w1_bus_master1: Family 0 for 00.600000000000.65 is not registered.
[  365.383779] w1_master_driver w1_bus_master1: Family 0 for 00.e00000000000.e9 is not registered.
[  424.451079] w1_master_driver w1_bus_master1: Family 0 for 00.100000000000.9d is not registered.
[  460.905545] w1_master_driver w1_bus_master1: Family 0 for 00.900000000000.11 is not registered.
[  531.571064] w1_master_driver w1_bus_master1: Family 0 for 00.500000000000.db is not registered.
[  580.012130] w1_master_driver w1_bus_master1: Family 0 for 00.d00000000000.57 is not registered.
[  604.621303] w1_master_driver w1_bus_master1: Family 0 for 00.300000000000.be is not registered.
[  651.181175] w1_master_driver w1_bus_master1: Family 0 for 00.b00000000000.32 is not registered.
[  687.921378] w1_master_driver w1_bus_master1: Family 0 for 00.700000000000.f8 is not registered.
[  736.345572] w1_master_driver w1_bus_master1: Family 0 for 00.f00000000000.74 is not registered.
[  794.843581] w1_master_driver w1_bus_master1: Family 0 for 00.080000000000.c2 is not registered.
[  844.152264] w1_master_driver w1_bus_master1: Family 0 for 00.880000000000.4e is not registered.
[  879.575110] w1_master_driver w1_bus_master1: Family 0 for 00.480000000000.84 is not registered.
[  927.002598] w1_master_driver w1_bus_master1: Family 0 for 00.c80000000000.08 is not registered.
[  998.594209] w1_master_driver w1_bus_master1: Family 0 for 00.280000000000.e1 is not registered.
[ 1057.993387] w1_master_driver w1_bus_master1: Family 0 for 00.a80000000000.6d is not registered.
[ 1117.520889] w1_master_driver w1_bus_master1: Family 0 for 00.680000000000.a7 is not registered.
[ 1154.964359] w1_master_driver w1_bus_master1: Family 0 for 00.e80000000000.2b is not registered.
[ 1214.104342] w1_master_driver w1_bus_master1: Family 0 for 00.180000000000.5f is not registered.
`

how can I "undo" the rpi-update?
