### ISSUE TITLE
libkmod: ERROR. Pointing to previous kernel.

### ISSUE THREAD

**Issue by Fourdee** [Hexxeh/rpi-update#192]
Hi,

This issue is probably caused by the kernel, rather than rpi-update. Also posted on RPi Git: https://github.com/raspberrypi/firmware/issues/474

Ran rpi-update. It upgraded to 4.1.7.
Removed the previous kernels (4.1.6).

No sound, libkmod pointing to previous kernel.
> root@dietpi:/#  modprobe snd_bcm2835
libkmod: ERROR ../libkmod/libkmod.c:554 kmod_search_moddep: could not open moddep file '/lib/modules/4.1.6-v7+/modules.dep.bin'
root@dietpi:/# ls -lha /lib/modules/
total 16K
drwxr-xr-x  4 root root 4.0K Sep 18 12:34 .
drwxr-xr-x 13 root root 4.0K Sep 18 12:21 ..
drwxr-xr-x  3 root root 4.0K Sep 18 12:25 4.1.7+
drwxr-xr-x  3 root root 4.0K Sep 18 12:25 4.1.7-v7+

Clearly, running the following fixes the issue:
> cp -R /lib/modules/4.1.7+ /lib/modules/4.1.6+
cp -R /lib/modules/4.1.7-v7+ /lib/modules/4.1.6-v7+
modprobe snd_bcm2835

**Comment by XECDesign** [comment]
Did you reboot?

**Comment by Fourdee** [comment]
> Did you reboot?
Turns out I didn't lol. 

Bad day at the office, complete user error. Apologies.

**Comment by XECDesign** [comment]
Happens
