### ISSUE TITLE
After Update, Raspberry Pi Crashes/Freezes

### ISSUE THREAD

**Issue by KyleBoyer** [Hexxeh/rpi-update#193]
After performing an update on my Raspberry Pi 2, and my buddies Raspberry Pi 2, we noticed that our Pis would randomly "black screen" and freeze after running for a bit. I'm not too privvy to check what logs could exist from this. The only known fix to get the pi "un-frozen" is to remove the power, and replace it. To note, the rpi-update worked successfully to update the Pi to the new version, however after this is when we started experiencing random crashing. So far, my Pi has crashed 3 times since last night, and it could be more if I was able to reset it as soon as it went down(but I couldn't because I sleep at night).

**Comment by popcornmix** [comment]
Firstly are you overclocking? If so, disable that and confirm the issue still occurs.

I'm not seeing other reports of this. You can use
``sudo rpi-update <hash>``
Using the hashes (the hex number at the end of each commi's URL) from https://github.com/Hexxeh/rpi-firmware/commits/master 
If you can identify the exact update that introduced the problem, we can investigate exactly what changed.

**Comment by KyleBoyer** [comment]
> Firstly are you overclocking? If so, disable that and confirm the issue still occurs.
> 
> I'm not seeing other reports of this. You can use:
> sudo rpi-update <hash>
> Using the hashes (the hex number at the end of each commi's URL) from https://github.com/Hexxeh/rpi-firmware/commits/master to downgrade to a specific firmware version.
> If you can identify the exact update that introduced the problem, we can investigate exactly what changed.

I am not overclocking. I will attempt downgrading to see if it changes anything!

**Comment by KyleBoyer** [comment]
I downgraded to "608c3b3e994e086d400f77469682ff1e8f346e27" 4.1.8 and it has fixed the issue so far. Thus the problem must be happening in one of the two latest firmware revisions. After a bit more testing, I can see if 4.1.9 also does not have the issue.

**Comment by popcornmix** [comment]
Thanks. I would be interested if 4.1.9 is good or bad.

**Comment by KyleBoyer** [comment]
> Thanks. I would be interested if 4.1.9 is good or bad.

Just installed 4.1.9 to test.

**Comment by KyleBoyer** [comment]
4.1.9 DOES have the same issue.

**Comment by simoncaron** [comment]
Hi, I'm new here but I can confirm that I also have update my pi2 to the latest firmware and I'm also getting freeze. Each time messages log is about cfg80211 and CRDA. I don't know why cfg80211 module is loaded since I don't use wi-fi.

**Comment by diluex** [comment]
it's the same for me. my raspberrypi is running as a server and freezing after 1-2 h and not responding over ssh after update. also reading crda an cfg80211 wihtout using wifi.

**Comment by popcornmix** [comment]
Please try latest rpi-update and report back.

**Comment by mbentley** [comment]
The latest has been working for me for the last 18 hours.

**Comment by simoncaron** [comment]
I'll give it a try and comeback with the results.

**Comment by popcornmix** [comment]
@KyleBoyer 
Pretty sure this is fixed. Please test and close if okay.

**Comment by KyleBoyer** [comment]
The latest version of the OS has (so far) fixed this issue. After successfully completing 48 hours without experiencing this issue again, I believe it is safe to say that this issue can now be closed.

**Comment by KyleBoyer** [comment]
I experienced this again on the latest update.

**Comment by popcornmix** [comment]
Can you confirm the exact firmware version that causes the problem?
Use ``sudo rpi-update <hash>`` with the has from then end of URLs from here: https://github.com/Hexxeh/rpi-firmware/commits/master

**Comment by KyleBoyer** [comment]
The most recent version as of 12 hours ago.

**Comment by popcornmix** [comment]
And reverting to the version before that fixes it? It's important to confirm exactly which firmware caused the problem.

**Comment by KyleBoyer** [comment]
I shall try reverting when I'm back at my computer, but over this past thanksgiving(USA Holiday) week, it went down while out of town in the same manner as before(when this ticket was opened). It took a day or so to crash, so I'll keep you posted.
