### ISSUE TITLE
Feature request: update kernel headers w/ kernel update

### ISSUE THREAD

**Issue by Fordi** [Hexxeh/rpi-update#195]
Really, I just don't know where to look to find a particular version of the Kernel headers, and I need to be able to build a realtek driver against what my Pi has been updated to (4.1.7-v7+).  I figure, since you're building a kernel and firmware modules, it's a safe bet you know where to get them.  I also figured it'd be _really_ nice if rpi-update had "UPDATE_HEADERS" as an option, since this is largely a trivial "download-and-unpack" task once you have a URL.

**Comment by popcornmix** [comment]
Not going to be supported by rpi-update.
This may be useful: https://github.com/notro/rpi-source/wiki
