### ISSUE TITLE
Clearing out older firmware updates after new release installed successfully by rpi-update

### ISSUE THREAD

**Issue by shaun10** [Hexxeh/rpi-update#197]
Just wondering if anyone has started working on modifications to remove older firmware files after updates have installed successfully. In the screenshot below about 860 MB is used for older firmware versions in /lib/modules

![screen shot 2015-11-09 at 7 51 12 pm](https://cloud.githubusercontent.com/assets/7233643/11054000/4bf21c80-871b-11e5-931a-c3e47b4a00c7.png)

Anyone think the option to automatically remove older versions would be helpful?

**Comment by popcornmix** [comment]
Okay, it's fair point. I've added an option to delete the unused modules directories when doing an update. Try:
```sudo PRUNE_MODULES=1 rpi-update```

If you are already up to date, run
``sudo rm /boot/.firmware_revision``
first to force an update.

**Comment by shaun10** [comment]
Worked perfectly:
![screen shot 2015-11-10 at 12 21 42 pm](https://cloud.githubusercontent.com/assets/7233643/11074639/a2dee746-87a5-11e5-918d-080e44a1a05f.png)

Freed up about 20% of my 8GB card which had only 5.2GB available with NOOBs. Much more lean. 

So in future just run with PRUNE_MODULES=1 parameter to update while only keeping one of the last module dirs right?

Thanks again

**Comment by popcornmix** [comment]
Yep
