### ISSUE TITLE
Install location is /boot not /boot/firmware

### ISSUE THREAD

**Issue by michaelfranzl** [Hexxeh/rpi-update#205]
The script installs the firmware and kernel files in FW_PATH, which is /boot. However, the Raspberry Pi needs them in /boot/firmware. I had to copy the files manually. Is there a reason for installing in /boot?

**Comment by popcornmix** [comment]
rpi-update is designed for raspbian which locates firmware and kernel in /boot.
If you are using a different distribution (ubuntu?) that locates things differently then I suspect your shouldn't be using rpi-update.

**Comment by michaelfranzl** [comment]
Ok thank you very much.
