### ISSUE TITLE
Running with -y parameter brakes down

### ISSUE THREAD

**Issue by szmaorka** [Hexxeh/rpi-update#210]
Running with -y parameter gives this error:
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by lurch** [comment]
The *only* (optional) parameter that rpi-update accepts is the git hash of a specific revision to update to https://github.com/Hexxeh/rpi-update#options

Unsurprisingly, there's no firmware revision that has a git hash of "-y"  ;-)

(although maybe there could be a check that the supplied hash is actually a valid commit ID, before piping the output of curl directly into tar)

**Comment by Ruffio** [comment]
@szmaorka can this issue be closed?

**Comment by szmaorka** [comment]
@Ruffio Have been added a warning if using an invalid parameter? If yes, of course we can close :)

**Comment by Ruffio** [comment]
@lurch ?

**Comment by popcornmix** [comment]
See: https://github.com/Hexxeh/rpi-update/commit/b19779b2c8b769b3bd2bc9fb4cf858f340a11cf5

@szmaorka @lurch please test.

**Comment by szmaorka** [comment]
@popcornmix Tested, works. Gives `Invalid git hash specified` error!
