### ISSUE TITLE
Add documentation for downgrading firmware / "un-install" rpi-update

### ISSUE THREAD

**Issue by crw** [Hexxeh/rpi-update#222]
Howdy! I kind of blindly ran rpi-update without _ahem_ closely reading the docs. I did not realize at the time that the apt-get updates would update rpi firmware to the latest stable before I did this. My request is, could you please add a section to the README.md covering how to uninstall the changes made by rpi-update and get back on the latest stable firmware? Thanks!

**Comment by Ruffio** [comment]
@crw You can't 'uninstall' but you can install ealier firmware by using Option: https://github.com/Hexxeh/rpi-update#options

**Comment by popcornmix** [comment]
```sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel```
will get you back to latest stable (apt-get) firmware/kernel.

**Comment by lemassykoi** [comment]
I used rpi-update to update to 4.9, unfortunately, my DomoticZ install hangs up because of issue with GPIO.
To revert, I used `sudo BRANCH=stable rpi-update` and it's all revert back nicely.

**Comment by Ruffio** [comment]
@crw can this be closed?

**Comment by crw** [comment]
Yep.
