### ISSUE TITLE
Graphics driver is broken with latest kernel firmware

### ISSUE THREAD

**Issue by abhisek-mishra** [Hexxeh/rpi-update#223]
If I do a sudo rpi-update and then enables the Graphic driver , black screen comes after reboot. If I disable the Graphic driver it works fine...

**Comment by Ruffio** [comment]
@abhisek-mishra is this still an issue? What is the 'Graphic driver'?

**Comment by Ruffio** [comment]
@abhisek-mishra this repro is only for rpi-update tool itself. This is the wrong place for this kind of issue. @popcornmix this issue should be closed due to wrong repro and lack of response for three months...
