### ISSUE TITLE
rpi-update breaks latest Raspbian PIXEL login after update

### ISSUE THREAD

**Issue by mitchhh22** [Hexxeh/rpi-update#224]
I installed a fresh copy of the new Raspbian released a few days ago. Everything works fine until I update the firmware with rpi-update. 
Now the Desktop login is broken. It tries to login but just flashes the screen and returns back to the login prompt.

**Comment by jgwatkins** [comment]
Same here.  Any luck?

**Comment by popcornmix** [comment]
I've tried rpi-update and it didn't cause any issue for me. @spl237 also doesn't see the issue.
First does reverting firmware back to version from last raspbian jessie release restore behaviour?
```sudo rpi-update 21505f3fb5d8e2a5abbf95baf441a7a6415d4a82```

**Comment by jgwatkins** [comment]
Thx Popcornmix!

Turns out i had a corrupt .Xauthority file.  I just deleted it and was able to login.  Appreciate your help! :)

**Comment by jgwatkins** [comment]
to mitchhh22:

I was able to fix this problem doing to following:

When the "greeter" screen is up and doing its endless login loop as you described:

SSH into the RPI with another local machine
type:
`ls -a`
look for a file named .Xauthority
delete .Xauthority `rm .Xauthority`

Hope this works

**Comment by popcornmix** [comment]
Pretty sure this issue is unrelated to rpi-update so closing.
If you have evidence for .Xauthority being corrupted (that isn't the fault of your own scripts) then please report here: https://github.com/RPi-Distro/raspberrypi-ui-mods
