### ISSUE TITLE
Rpi-update is broken with the latest update to firmware

### ISSUE THREAD

**Issue by ngineerken** [Hexxeh/rpi-update#227]
if I run sudo BRANCH=next rpi-update
and I get this error:
*** Relaunching after update
/usr/bin/rpi-update: line 2: syntax error near unexpected token `newline'
/usr/bin/rpi-update: line 2: `<?xml version="1.0" encoding="utf-8"?>'

I have reinstalled rpi-update using:
sudo apt-get install --reinstall rpi-update

I have even purged & reinstalled:
sudo apt-get purge rpi-update
sudo apt-get install rpi-update

I have tried without BRANCH=next
sudo rpi-update
/usr/bin/rpi-update: 3: /usr/bin/rpi-update: Syntax error: newline unexpected

but the error persists

**Comment by popcornmix** [comment]
Github was down recently. Possibly your /usr/bin/rpi-update contains some sort of github error page.
Try:
```
sudo wget https://raw.githubusercontent.com/Hexxeh/rpi-update/master/rpi-update -O /usr/bin/rpi-update
```
and then run rpi-update again.

**Comment by ngineerken** [comment]
That fixed the issue.

Thank you
