### ISSUE TITLE
Say Yes to rpi-update

### ISSUE THREAD

**Issue by rockrabbit** [Hexxeh/rpi-update#232]
I've noticed since the latest firmware updates, I have to say YES to do the firmware update.

I wrote a script that is triggered by a cronjob to run once a month to do firmware updates... 

I've tried `sudo rpi-update -y` but that fails!

Is there a way to auto say Yes?

**Comment by popcornmix** [comment]
``sudo SKIP_WARNING=1 rpi-update``

**Comment by rockrabbit** [comment]
Oh thank you ever so much!
