### ISSUE TITLE
Force yes command

### ISSUE THREAD

**Issue by Reagn0x** [Hexxeh/rpi-update#241]
Hello,

when you have the message :
#############################################################
WARNING: This update bumps to rpi-4.9.y linux tree
Be aware there could be compatibility issues with some drivers
Discussion here:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=167934
##############################################################
Would you like to proceed? (y/N)

Is it possible to add an argument for force the answer yes like "rpi-update --force-yes"

Thanks

**Comment by popcornmix** [comment]
Try ``sudo SKIP_WARNING=1 rpi-update``
