### ISSUE TITLE
RPi 2B Update stops when downloading!

### ISSUE THREAD

**Issue by Xie-Tian** [Hexxeh/rpi-update#250]
Hi,
When I run rpi-update it doesn't seem to be finishing the downloads for the updates it is doing. 
It ends with following:
```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
Also, my ssh to other IP address `ssh pi@IPaddress` will also disconnect in several seconds after successfully connecting.
Is this a local network issue? But I tried ping to other ip address `ping google.com,` 43% packet loss
Does anyone have the idea?
Thanks!

**Comment by popcornmix** [comment]
This sounds like a local network issue. Nothing to do with rpi-update.

You can test this just by trying to download the firmware directly from pi:
```
wget  https://github.com/Hexxeh/rpi-firmware/tarball/master
```

**Comment by Xie-Tian** [comment]
I tried for 4 hours, but it just continued loading and ended with "Read error at byte xxxxxx Resource temporarily unavailable, try again. Retrying". And begin with another loading....

**Comment by popcornmix** [comment]
Are you connecting Pi through wired ethernet or wifi?

**Comment by Xie-Tian** [comment]
Thanks! No problem now because I don't need to update my pi. Thanks a lot!
