### ISSUE TITLE
Boot fails after update when new kernel is installed and SD card encrypted

### ISSUE THREAD

**Issue by fis-cz** [Hexxeh/rpi-update#252]
Just would like to let you know that if initramfs is in use and rpi-update performed with a new kernel the initramfs is not updated and it is not possible to boot as there are no appropriate kernel modules to be used by cryptsetup.

It would be great if you can call some initramfs standard hook or all scripts in /etc/kernel/postinst.d/ folder with the installed kernel version as a only the one parameter. In this case it will be possible to write srcipts for refreshing the image if the new kernel is installed.

See https://robpol86.com/raspberry_pi_luks.html for details.

**Comment by dsx724** [comment]
It would be great if this tool used /etc/default/raspberrypi-kernel's INITRD settings and update initrd as appropriate. That way this tool doesn't break booting for users that don't manually update initramfs. Kernel updates should go along with initramfs updates.

**Comment by popcornmix** [comment]
See also: https://github.com/Hexxeh/rpi-firmware/issues/200

**Comment by eljoest** [comment]
The regular kernel is calling something like ```run-parts -v --report --exit-on-error --arg=4.19.97-v7l+ --arg=/boot/kernel7l.img /etc/kernel/postinst.d``` after installation for each kernel image.
Custom hooks could then take care of the initrd generation. I've posted one to eljoest/rpi-initramfs-tools@394fd86ae6bece441d06b907442520f4e06579d9 Not sure if it's still useful.

**Comment by Ruffio** [comment]
@fis-cz  can this be closed?

**Comment by fis-cz** [comment]
Absolutely.

On 28. 12. 2020, at 13:52, Rasmus Christiansen <notifications@github.com> wrote:

﻿

@fis-cz<https://github.com/fis-cz> can this be closed?

**Comment by Ruffio** [comment]
@popcornmix  please close this per originator confirmation.
