### ISSUE TITLE
Update firmware from own update server?

### ISSUE THREAD

**Issue by Rosentorp** [Hexxeh/rpi-update#257]
Hi all!

We have a system where we have remove all apt-get servers except for our own one. Is there a possibility to use this server for the firmware update as well?

As far as I can ses then we can also control the version to be used as well.

/Anders

**Comment by popcornmix** [comment]
You can set ``REPO_URI`` to download from a different github address. The default is ``https://github.com/Hexxeh/rpi-firmware`` but you can change that.

**Comment by Ruffio** [comment]
@Rosentorp can this issue be closed?

**Comment by Rosentorp** [comment]
Yes, thanks!

Issue solved.

Anders



Skickat från min Galaxy



-------- Originalmeddelande --------
Från: Rasmus Christiansen <notifications@github.com>
Datum: 2020-12-25 10:12 (GMT+01:00)
Till: Hexxeh/rpi-update <rpi-update@noreply.github.com>
Kopia: Anders Nilsson <anders.nilsson@365id.com>, Mention <mention@noreply.github.com>
Ämne: Re: [Hexxeh/rpi-update] Update firmware from own update server? (#257)


@Rosentorp<https://github.com/Rosentorp> can this issue be closed?

**Comment by Ruffio** [comment]
@Rosentorp ok, then please close this issue. Thanks :-)
