### ISSUE TITLE
element14 RASPBERRYPI-DISPLAY not work 

### ISSUE THREAD

**Issue by reininnjp** [Hexxeh/rpi-update#258]
I updated kernel to  4.9.79-v7+ by rpi-update.
And found element14 RASPBERRYPI-DISPLAY does not work.
What's wrong?

**Comment by reininnjp** [comment]
Kernel 4.14.18-v7 looks good!
But touchscreen calibration seems not work.

**Comment by popcornmix** [comment]
Calibration is likely to be an X issue rather than a kernel issue, so you would be better off asking in forum.

**Comment by Ruffio** [comment]
@reininnjp can this be closed?

**Comment by Ruffio** [comment]
@popcornmix this issue has stalled without any response from originator for three months. Should be closed IMHO.
