### ISSUE TITLE
no  kernel headers

### ISSUE THREAD

**Issue by dissipator** [Hexxeh/rpi-update#262]
I update to 4.14.48
but no kernel head in my system when i install  seeed-voicecard -v 0.3
dkms add -m seeed-voicecard -v 0.3
DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.14.48+ cannot be found at
/lib/modules/4.14.48+/build or /lib/modules/4.14.48+/source.

**Comment by kregory** [comment]
You Have to install kernel-header

sudo apt-get install kernel-header

Le mar. 12 juin 2018 à 11:42, dissipator <notifications@github.com> a
écrit :

**Comment by dissipator** [comment]
yes only 4.9.+ header

**Comment by popcornmix** [comment]
Are you using an updated raspbian stretch distribution? That should be on 4.14.
You may also want to consider this: https://github.com/notro/rpi-source/wiki

**Comment by dissipator** [comment]
OK ,I will try.thanks.......

**Comment by dissipator** [comment]
*** Create /lib/modules/<ver>/{build,source} symlinks

 *** .config

 *** Module.symvers

 *** make modules_prepare
  HOSTCC  scripts/basic/fixdep
/bin/sh: 1: scripts/basic/fixdep: Permission denied
scripts/Makefile.host:102: recipe for target 'scripts/basic/fixdep' failed
make[2]: *** [scripts/basic/fixdep] Error 126
Makefile:463: recipe for target 'scripts_basic' failed
make[1]: *** [scripts_basic] Error 2
make: *** No rule to make target 'modules_prepare'。 停止。
Traceback (most recent call last):
  File "/usr/bin/rpi-source", line 379, in <module>
    sh("cd %s && make modules_prepare %s" % (linux_symlink, (" > /dev/null" if args.quiet else "")))
  File "/usr/bin/rpi-source", line 85, in sh
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /app/root/linux && make modules_prepare ' returned non-zero exit status 2

use the root user.

**Comment by dissipator** [comment]
the same as:
https://github.com/raspberrypi/linux/issues/2579

**Comment by Ruffio** [comment]
@dissipator is this issue still relevant?

**Comment by Ruffio** [comment]
@dissipator is this issue still relevant?

**Comment by Ruffio** [comment]
This issue is stall. Please consider to close.
