### ISSUE TITLE
[feature request] Reboot option after successfully update

### ISSUE THREAD

**Issue by nonflammable** [Hexxeh/rpi-update#263]
Is possible to add reboot option ?
sudo RPI_REBOOT=1 rpi-update
only after successfully update.
Or add exit code other than 0 when reboot is needed.
It can be helpful to automate updates.

**Comment by popcornmix** [comment]
Try now:
https://github.com/Hexxeh/rpi-update/commit/866c310bab84d1c2bd8990b7d7b6154e7915f9fc

**Comment by nonflammable** [comment]
Thanks, everything works. I think the readme file can be updated.
