### ISSUE TITLE
After rpi-update my pi zero it is death?

### ISSUE THREAD

**Issue by borgelite** [Hexxeh/rpi-update#266]
Hi i update my pi zero with this command.
rpi-update 8234d5148aded657760e9ecd622f324d140ae89
and after complet this and i reboot.
The zero dont blinking his leds and no ssh.
Can i flash the chip on the rpi directly?

**Comment by MrEngman** [comment]
Why did you use that command? It loads kernel 3.6.11+ #557 from Oct 18 2013.

This is many years (4 ?) before the Pi Zero was made and will not work on the Pi Zero.

You need to download the kernel image from [](url) and copy the image to your SD card.

**Comment by MrEngman** [comment]
Why did you use that command. It loads kernel 3.6.11+ #557 from Oct 18 2013, about 3-4 years before the Pi Zero appeared so it will not work on the Pi Zero.

Download the kernel image from https://www.raspberrypi.org/downloads/raspbian/ and use that kernel instead.
