### ISSUE TITLE
Segmentation fault      depmod -b "${ROOT_PATH}" -a "${BASEDIR}"

### ISSUE THREAD

**Issue by alatteri** [Hexxeh/rpi-update#276]
I went to do a full update today.  Did apt-get update ; apt-get upgrade ; reboot
That all finished successfully, then tried rpi-update

root@DNS01:~# rpi-update 
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
#############################################################
WARNING: This update bumps to rpi-4.19.y linux tree
Be aware there could be compatibility issues with some drivers
Discussion here:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=224931
##############################################################
Would you like to proceed? (y/N)
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    542      0 --:--:-- --:--:-- --:--:--   543
100 58.3M  100 58.3M    0     0   785k      0  0:01:16  0:01:16 --:--:-- 1333k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 4.19.34+
/usr/bin/rpi-update: line 94:   785 Segmentation fault      depmod -b "${ROOT_PATH}" -a "${BASEDIR}"

**Comment by lurch** [comment]
`rpi-update` shouldn't be considered part of a "full update", and you ought to be using `dist-upgrade` rather than `upgrade`. See https://www.raspberrypi.org/documentation/faqs/#pi-software
