### ISSUE TITLE
Invalid hash given

### ISSUE THREAD

**Issue by GabrielKn8** [Hexxeh/rpi-update#277]
"Would you like to proceed?" does not accept "y".

**Comment by mbaccia514** [comment]
Also had this issue on a (relatively) fresh install. After performing apt updates the rpi-update command aborts with "Invalid git hash specified". Gives the same error when specifying different hashes as well.

See also:
https://github.com/Hexxeh/rpi-update/issues/261

**Comment by ricktendo** [comment]
Yes, this error still happening to me since yesterday.

**Comment by pucelev** [comment]
I tried this morning and I'm also getting this error

**Comment by Shadesh** [comment]
Please make sure you don't (DNS or whatever) block GitHub Domains. For me it was "codeload.github.com" which was blocked by PIHole.

That prevented a successful download of fresh firmware with rpi-update.

**Comment by pucelev** [comment]
Thanks Shadesh!  I disabled Pihole and was able to do the rpi-update.

**Comment by ricktendo** [comment]
Yes, it was Pi-Hole

**Comment by popcornmix** [comment]
I've added  a warning in troubleshooting section of readme about pi-hole blocking.

I further todo would be to detect the dns block directly by the tool.

Can someone with pi-hole set up to block report the output of:
```curl https://api.github.com/repos/Hexxeh/rpi-firmware/commits/master```

**Comment by ricktendo** [comment]
Yes it does allow api.github.com, only codeload.github.com was blocked as malicious by the following two block lists:

1) https://www.squidblacklist.org/downloads/dg-malicious.acl
2) https://hosts-file.net/emd.txt

FYI I get my Pi-Hole blocklists from the following site: https://firebog.net/

I use the ticked lists: https://v.firebog.net/hosts/lists.php?type=tick

**Comment by peatrick** [comment]
I guess I'll also chalk this one up to Pi-hole related issues.  Disabled (both) Pi-hole(s) and adjusted **/etc/resolv.conf** to use `nameserver 1.1.1.1` instead of my Unbound server(s) at 127.0.0.1 / localhost and am now happily using:
> `Linux pihole2 4.19.40-v7+ #1217 SMP Tue May 7 17:22:08 BST 2019 armv7l GNU/Linux`

**Comment by qyqsoft** [comment]
You have to whitelist **codeload.github.com** in your pi-hole. That solved the issue for me.

**Comment by OliverGruenberg** [comment]
just wanted to update kernel to v4.19.57-v7+ via 
sudo rpi-update 6e787b87ace9f945f17a9022288e2758ed281cf7

results in
 *** Invalid hash given

no pi-hole running btw

**Comment by OliverGruenberg** [comment]
got it: the provided git hash in
https://github.com/Hexxeh/rpi-firmware/blob/master/git_hash
was incorrect.
The correct one for kernel v4.19.57 is:
 f8060224e53e26cdaea5b9f6f010ac8c3692e2ea

**Comment by popcornmix** [comment]
https://github.com/Hexxeh/rpi-firmware/blob/master/git_hash

is the git hash of the kernel used to build the image. e.g.
https://github.com/raspberrypi/linux/commit/6e787b87ace9f945f17a9022288e2758ed281cf7

It is correct.

**Comment by billouetaudrey** [comment]
Hi same issue when I used cloudflare dns

**Comment by Ruffio** [comment]
@GabrielKn8 has this issue been resolved?

**Comment by GabrielKn8** [comment]
@Ruffio l gave up on this. So, no update on my end.

**Comment by pelwell** [comment]
These aren't problems that rpi-update can solve.

**Comment by Zeguym** [comment]
> Also had this issue on a (relatively) fresh install. After performing apt updates the rpi-update command aborts with "Invalid git hash specified". Gives the same error when specifying different hashes as well.
> 
> See also:
> #261

I had the same problem and it was missing public_repo right in the github access token

**Comment by maguilara** [comment]
My "apt update && upgrade" failed for some reason and kernel modules didn't match the one that I had currently installed, and rpi-update-ing to the corresponding commit with the matching kernel version didn't work with this exact error. 
I had not DNS issues, my pihole went down with my docker (which is why I realized something was wrong with the upgrade) and I didn't use the pihole dns on my raspberry pi anyway. 
I managed to solve it by downloading the whole firmware repo to that exact commit, and replaced /boot/ directory with the /boot/ directory from the branch downloaded Rebooted and it took minute to load correctly, but it went fine. Hopefully this helps someone. 
I recommend taking a backup of your SD before doing this! I didn't do it, but it was a risk I took, doesn't need to be your case!

**Comment by gatedfuzz** [comment]
>  My "apt update && upgrade" failed for some reason and kernel modules didn't match the one that I had currently installed, and rpi-update-ing to the corresponding commit with the matching kernel version didn't work with this exact error. 
> 
> I had not DNS issues, my pihole went down with my docker (which is why I realized something was wrong with the upgrade) and I didn't use the pihole dns on my raspberry pi anyway. 
> 
> I managed to solve it by downloading the whole firmware repo to that exact commit, and replaced /boot/ directory with the /boot/ directory from the branch downloaded Rebooted and it took minute to load correctly, but it went fine. Hopefully this helps someone. 
> 
> I recommend taking a backup of your SD before doing this! I didn't do it, but it was a risk I took, doesn't need to be your case!




Same thing just happened to me because my time was exactly 5 hours out of sync. Strange.

**Comment by maguilara** [comment]
> Same thing just happened to me because my time was exactly 5 hours out of sync. Strange.

Well, mine wasn't out of sync AFAIK, last reboot was less than 2 days ago, not enough time for me to detect that it was out of sync. And I believe the system asks for new time periodically either way. But my timezone is UTC-5, not sure if that is related or not.

**Comment by gatedfuzz** [comment]
> > Same thing just happened to me because my time was exactly 5 hours out of sync. Strange.
> 
> 
> 
> Well, mine wasn't out of sync AFAIK, last reboot was less than 2 days ago, not enough time for me to detect that it was out of sync. And I believe the system asks for new time periodically either way. But my timezone is UTC-5, not sure if that is related or not.

its funny because i cant get mine to sync back now. i was about to reflash anyway after i spent the evening seeing how quickly i could break it, guess i didnt have to try that hard.
