### ISSUE TITLE
Soften Pi4 check_partition for use in directory destination

### ISSUE THREAD

**Issue by macmpi** [Hexxeh/rpi-update#281]
ref https://github.com/Hexxeh/rpi-update/commit/882f5c188dce31365885c8ff23724749294bf8c1

`check_partition` addition is causing issues on usecases where rpi-update is used to build distributions: in such case destination may be a simple directory rather than a partition per say.
Could this check be done in a "softer" manner, to play nice with such usecases?

Would be nice if `WANT_PI4` usage is explained in `README.md` expert options too.
Thanks for consideration.

**Comment by volumio** [comment]
Made a pull request: https://github.com/Hexxeh/rpi-update/pull/282

**Comment by Ruffio** [comment]
@popcornmix what is status on this?

**Comment by Ruffio** [comment]
@macmpi isn't this scenario covered by the merge of #283 ?
Can this be closed?

**Comment by Ruffio** [comment]
@macmpi can this issue be closed?

**Comment by macmpi** [comment]
sure, thanks.
