### ISSUE TITLE
RPi3b+ won't boot

### ISSUE THREAD

**Issue by dev18-future** [Hexxeh/rpi-update#284]
Hello I run PiServer and when I start raspberry it stuck  on boot after rpi-update can I rollback on previus kernel

**Comment by kapitainsky** [comment]
before upgrading firmware it is always good idea to image your SD card. If anything goes wrong just re-flash it from backup. RPi guys included warnings now that rpi-update is not something people should run without clear reason.

**Comment by kapitainsky** [comment]
also look at the issue #273 . In your case if you can't ssh you can still do it on external machine.

**Comment by Ruffio** [comment]
@dev18-future can this be closed?
