### ISSUE TITLE
reinstall firmware

### ISSUE THREAD

**Issue by actraiser30** [Hexxeh/rpi-update#288]
Hello

i want to reinstall the same firmware i have in my raspberry and not a newer/beta one

how can i do it? 

and how can i install a specific firmware revision?

thanks

**Comment by popcornmix** [comment]
What version do you want?
If the current apt version, then
```
sudo apt-get install --reinstall raspberrypi-bootloader
sudo apt-get install --reinstall raspberrypi-kernel
```
If it's a specific historical rpi-update version, then look at:
https://github.com/Hexxeh/rpi-firmware/commits/master

If you click on each commit the end of the url contains a git hash. Run
```sudo rpi-update <hash>```
to update to that version.

**Comment by Ruffio** [comment]
@actraiser30 has the issue been resolved and this can be closed?

**Comment by Ruffio** [comment]
this issue should be closed due to inactivity for three months
