### ISSUE TITLE
Updates are not displayed with JUST_CHECK=1 rpi-update

### ISSUE THREAD

**Issue by Nastras** [Hexxeh/rpi-update#290]
Hello,

I have the following problem.

when I run sudo JUST_CHECK=1 rpi-update I get nothing displayed except this:

` *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** We're running for the first time
 *** Firmware update required. No local hash to compare to.
`

If I do the same thing on another Pi, all updates will be displayed.

` *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** We're running for the first time
 *** Firmware update required. New commits available:
======================================================
Commit: kernel: Bump to 4.19.57`
`

Can someone tell me why nothing is displayed?

Thanks!

**Comment by popcornmix** [comment]
It compares the current rpi-update version to the latest version and prints out the commit messages between. If you have never run rpi-update then this doesn't make sense.

The local hash it is looking for is ``/boot/.firmware_revision``

**Comment by Nastras** [comment]
Thanks for your answer.
This message occurred at first start and does not disappear.

Do you have any idea how I can fix the error?

**Comment by Nastras** [comment]
I just looked up the directory /boot/.firmware_revision is not available in my system. I created it manually but the error still exists -.-

**Comment by popcornmix** [comment]
How did you create it?

**Comment by Nastras** [comment]
I created the folder with mkdir as root. Is that wrong?
![B7C21996-16DD-4DCD-88B2-EB01B500349F](https://user-images.githubusercontent.com/27686185/70083540-dfe58100-160c-11ea-9b96-c716b4157510.jpeg)

**Comment by popcornmix** [comment]
The file needs to contain the git hash of the last rpi-update.
This list of commits since the last run of rpi-update only makes sense on the second update.
If you haven't run rpi-update before we don't know what has changed since the last one.

Once you have run rpi-update once, you can use ``JUST_CHECK=1 rpi-update``

**Comment by Nastras** [comment]
I started rpi update now but without installing it. Unfortunately it still doesn't work JUST_CHECK=1 rpi-update. 

I just want to see the upcoming firmware updates with rpi-update 😁?
![FF21F956-70B5-4ACD-B157-68DF682B1219](https://user-images.githubusercontent.com/27686185/70084489-9eee6c00-160e-11ea-89fa-f454cfdb10e6.jpeg)

**Comment by Nastras** [comment]
Thank you for your help!

**Comment by popcornmix** [comment]
Did you delete the directory you created ``/boot/.firmware_revision``?
That will stop rpi-update from being able to create the *file* ``/boot/.firmware_revision``

**Comment by Nastras** [comment]
No, I haven't. But I did it now and did rpi-update again. The error still exists.

![D18F0D53-AA3B-40AA-A4BD-774C6ED2AB07](https://user-images.githubusercontent.com/27686185/70085088-e0cbe200-160f-11ea-8960-ad8f7149ea19.jpeg)
![5677BA40-0EB8-4ED9-965E-15E89A912CDE](https://user-images.githubusercontent.com/27686185/70085093-e1647880-160f-11ea-8285-72dd158d6131.jpeg)

**Comment by popcornmix** [comment]
Did you enter "y" when asked "Would you like to proceed (y/N)" ?
You should see a ``*** Downloading specific firmware revision (this will take a few minutes)`` message which I don't see in your screenshot.

**Comment by Nastras** [comment]
Hello, I have now confirmed with y and installed the updates. Now it works.

Actually I didn't want to install any updates and I just wanted to see the updates.


Fortunately everything still works.

Thanks for your help and effort.

**Comment by popcornmix** [comment]
To just see the updates without running rpi-update you can browse:
https://github.com/Hexxeh/rpi-firmware/commits/master

**Comment by Nastras** [comment]
Thank you for the hint. I get the information by telegram push so I use rpi-update.
