### ISSUE TITLE
It will be nice to have option to update to latest bootloader EEPROM

### ISSUE THREAD

**Issue by xlazom00** [Hexxeh/rpi-update#293]
It will be nice to have option to update to latest bootloader EEPROM
to testing version

**Comment by popcornmix** [comment]
This is handled by the rpi-eeprom package.
https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md
https://www.raspberrypi.org/forums/viewtopic.php?t=250368

**Comment by Ruffio** [comment]
@xlazom00 please close this issue if it has been resolved. Thanks.
