### ISSUE TITLE
Ubuntu-Mate 16.04 having the same issues with kernel rpi-update 5.4.42-v7+ on Raspberry Pi 3

### ISSUE THREAD

**Issue by mrusli70** [Hexxeh/rpi-update#302]
Hi

Just to let you know that running with Raspberry Pi 3 on Ubuntu-Mate 16.04 and updating to version 5.4.42-v7+ did not work again. Cannot reboot and giving No Signal on HDMI. 

Guys I need to have support on this newer version of kernel support for raspberry pi 3 on Ubuntu-Mate 16.04. 

Have to revert back to the older kernel 4.19.114-V7+ again.

**Comment by pelwell** [comment]
We can't support other distributions. You can try contacting Canonical, but they'll probably suggest you to update to Ubuntu Mate 20.04.

**Comment by mrusli70** [comment]
Ok thanks pelwell.
