### ISSUE TITLE
Firmware not activated - ubuntu

### ISSUE THREAD

**Issue by bjajoh** [Hexxeh/rpi-update#307]
Hi, 

I tried to use this tool to install the raspbian kernel on the official ubuntu 18 and 20 image. No errors occur but uname -a still shows the old default kernel.

**Comment by pelwell** [comment]
That's not really our problem, but if you look in config.txt you'll probably find a line that says "kernel=<some name>" - try commenting it out by putting a "#" in front of it.

**Comment by bjajoh** [comment]
I didn't work, but thanks for your reply! :)
