### ISSUE TITLE
pi@raspberrypi:~ $ sudo rpi-update  *** Github API is currently rate limited - please try again after

### ISSUE THREAD

**Issue by liuyanghan** [Hexxeh/rpi-update#313]
Has anyone ever encountered these problems?

**Comment by pelwell** [comment]
Yes - I already told you what to do in https://github.com/Hexxeh/rpi-update/issues/253

**Comment by Ruffio** [comment]
@liuyanghan can this issue be closed?

**Comment by Ruffio** [comment]
This issue is stall. Please consider to close.
