### ISSUE TITLE
Latest firmware update showing 64bit on 32bit OS (armv7l vs aarch64)

### ISSUE THREAD

**Issue by gaamaaresosa** [Hexxeh/rpi-update#329]
I use older **Buster 32bit OS on Raspberry Pi 4** for Omxplayer option.
May I know why the latest firmware shows **64bit on 32bit OS (armv7l vs aarch64)**
Usually we identify the OS type by uname -a **armv7l**, but this latest firmware confusing.

Also the latest firmware changing the Hardware ID too. Which I used for some Fingerprint validation and now its failing.
Hardware      : **BCM2711**
vs
Hardware      : **BCM2835**

Kindly see the below comparison:

**OLDER FIRMWARE:**
           `pi@raspberrypi:~ $ /opt/vc/bin/vcgencmd version
            Feb 22 2023 10:46:02
            Copyright (c) 2012 Broadcom
            version 74a4b109e7f5be465332a1f102649d34f8498d05 (clean) (release) (start)`
            
            `pi@raspberrypi:~ $ uname -a
            Linux raspberrypi 6.1.14-v7l+ #1633 SMP Thu Mar  2 11:05:28 GMT 2023 **armv7l** GNU/Linux`

pi@raspberrypi:~ $ cat /proc/cpuinfo
Hardware      : **BCM2711**
Revision        : b03114
Serial            : 10000000a21fc55f
Model           : Raspberry Pi 4 Model B Rev 1.4

**LATEST FIRMWARE:**
            `pi@raspberrypi:~ $ /opt/vc/bin/vcgencmd version
            Mar 17 2023 10:50:39
            Copyright (c) 2012 Broadcom
            version 82f3750a65fadae9a38077e3c2e217ad158c8d54 (clean) (release) (start)`
           
            `pi@raspberrypi:~ $ uname -a
            Linux GB-SRI-SAI 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 **aarch64** GNU/Linux
            sudo rpi-update 82f3750a65fadae9a38077e3c2e217ad158c8d54`

pi@raspberrypi:~ $ cat /proc/cpuinfo
Hardware      : **BCM2835**
Revision        : b03114
Serial            : 10000000a21fc55f
Model           : Raspberry Pi 4 Model B Rev 1.4

**Comment by pelwell** [comment]
Wrong repo again - use https://github.com/raspberrypi/rpi-update/issues.
