### ISSUE TITLE
rpi-update - Not receiving objects

### ISSUE THREAD

**Issue by TisLars** [Hexxeh/rpi-update#79]
After doing the commands:

    sudo apt-get update && sudo apt-get upgrade
    sudo apt-get install ca-certificates
    sudo wget http://goo.gl/1BOfJ -O /usr/bin/rpi-update && sudo chmod +x /usr/bin/rpi-update
    sudo apt-get install git-core

And finally:

    sudo rpi-update

The process is stuck at Receiving Objects.

![github_problem](https://f.cloud.github.com/assets/1890311/305517/e840f3da-965b-11e2-84d8-9559f6a549bd.PNG)

**Comment by Ruffio** [comment]
As this issue is more than 1½ year old it must have been fixed and the issue is stalled. This should be closed.

**Comment by EMCP** [comment]
This issue JUST occurred for me :( on a Raspberry Pi B+

not sure what to do, trying to get my HiFi Berry installed
