### ISSUE TITLE
Use wget/zip instead of Git

### ISSUE THREAD

**Issue by LordMike** [Hexxeh/rpi-update#95]
I was just wondering, why not use wget to fetch the firmware?
It is possible, with Github, to download the entire repository as a .zip file

F.ex. here
https://codeload.github.com/Hexxeh/rpi-firmware/zip/master

Or here, for a specific revision
https://codeload.github.com/Hexxeh/rpi-firmware/zip/d5b05be2147bf5dc0137798837af24b0bbbe398d

Then you won't need to clone the repository with history and all, but instead just need to unzip the file.

**Comment by xyd945** [comment]
when I use wget down a compressed file, e.g., tar, tar.gz or zip file, I failed  to un-zip them. Error is: Can't extract files from the archive, you missed the archive name! 

any idea about that???

**Comment by popcornmix** [comment]
Post the exact commands you entered and errors reported and we may be able to help.

**Comment by xyd945** [comment]
I use Raspian, the OS in my raspberry pi. Compressed a folder to tar.gz file, and then I uploaded it to my github repository in the master branch. 

Then I click the tar.gz file, and copy the link in the address bar, and use wget http://aaa/aa/aaa/file.tar.gz, it will download the file into my raspberry pi.

then I use tar -xzvf file.tar.gz to unzip it. it tells you that it cannot extract, there is no archive. Very strange thing is when I use the download button in github to download the same file, it works well.

**Comment by popcornmix** [comment]
Please post the actual wget url, not one with aaa/aaa.

**Comment by lurch** [comment]
You probably just need to get the right link to the 'raw' URL, rather than the HTML preview that Github offers you by default.

**Comment by GrmpCerber** [comment]
@xyd945  could you try to run the `file` command on the file you downloaded ?
(eg. `file file.tar.gz`)
It should say something like "ZIP", if it states HTML or EMTPY, then the link is the problem
